### PR TITLE
Update dependencies and base image

### PR DESCRIPTION
**Pull request by merzi**
debian slim 11.5
SKALIBS 2.12.0.1
EXECLINE 2.9.0.1
S6 2.11.1.2
RSPAMD 3.4
GUCCI 1.6.5

### CODE REVIEW

**Comment by AndrewSav** [comment]
@merzi thank you for this, have you build the mailserver image based on this, ran the tests suite and made sure that the new image seems to work?

**Comment by merzi** [comment]
i build the images and build a mailserver image based on this build. 
This build runs without errors for 2 days on my server.

**Comment by AndrewSav** [comment]
Thank you for confirming this. The rspamd build is producing inordinate amount of warning this time around, it was not the case for the last build. While it still does build, I'm a bit worried if those warning indicate any problems we should be aware off. I try to search for them and may be ask in rspamd community

**Comment by AndrewSav** [comment]
I asked the question here: https://github.com/rspamd/rspamd/discussions/4353

**Comment by AndrewSav** [comment]
It looks like we can safely ignore these warning

**Pull request merged**
