### PR TITLE
Update gucci to 1.3.0

### PR DESCRIPTION
**Pull request by SaraSmiseth**

### CODE REVIEW

**Comment by AndrewSav** [comment]
This is not meant as a critique, just a curiosity, is there any advantage in this (and similar) updates for gucci, s6, scalib, execline apart from the obvious "keeping healthy/maintained" reason? @SaraSmiseth

**Comment by AndrewSav** [comment]
The gucci update seems to have changed the [default](https://golang.org/pkg/text/template/#Template.Option) from `missingkey=default` to `missingkey=error`. For us it should not matter as long as we do not have missing keys. This is probably worth double checking although at the moment I'm not sure how.

**Comment by SaraSmiseth** [comment]
> This is not meant as a critique, just a curiosity, is there any advantage in this (and similar) updates for gucci, s6, scalib, execline apart from the obvious "keeping healthy/maintained" reason? @SaraSmiseth

No other reason than keeping it healthy/maintained.
I have rss subscriptions for new updates of our dependencies and I just update when there are new versions and I have the time.

> The gucci update seems to have changed the [default](https://golang.org/pkg/text/template/#Template.Option) from `missingkey=default` to `missingkey=error`. For us it should not matter as long as we do not have missing keys. This is probably worth double checking although at the moment I'm not sure how.

I have build the main image with these changes and the tests run successfully. We have tests that make sure that there are no untransformed variables left in config files.

**Review by sknight80 — APPROVED** [review]
Looks good to me.  Thank you for updating the core image.

**Review by AndrewSav — APPROVED** [review]

**Comment by AndrewSav** [comment]
LGTM

**Pull request merged**
